### PR TITLE
Rewrote linked list functionality to resizable arrays, rm array constructors in fn/routine calls, other small fixes, all this for Intel/MPI compatibility

### PR DESCRIPTION
**Pull request by ringholm**
## Description

The linked list functionality for caching has been rewritten to use resizable arrays in place of a "pointer-based" linked list structure. I have for now disabled the restarting functionality but it's commented out and can be reinstated with some further work to adapt it to this new caching style (I know, commented-out code is not so great).

In most files, I have removed most or all use of array constructors in arguments to routines or functions and instead constructed the same arguments outside the context of the call itself. Such arguments have frequently been put into generically named variables. This change has been done in order to allow inside the routines called to modify or store the arguments that are used, e.g. for caching purposes. This seems to have been OK to do even with the array constructors for GNU compilers, but may have caused problems with Intel/MPI.

Finally there are some other minor bugfixes, some or all of which for bugs may have been introduced during the changes described above, so in those cases no "net bugfixing" over what is in master before this PR.

## Motivation and Context

This chance should allow OpenRSP to be run properly also when compiled in an Intel/MPI setup. It fixes the LSDalton issue https://gitlab.com/dalton/lsdalton/issues/35 .

## How Has This Been Tested?

I ran OpenRSP's unit test in an Intel/OpenMPI setup and I ran the LSDalton integration tests of OpenRSP in Intel/OpenMPI and Intel/Intel MPI setups. All attempted tests pass except possibly using "release" build setup of LSDalton with Intel/Intel MPI. But when building this latter again in relase mode with -fbacktrace and -g3 compiler flags added, the tests pass again.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change) 
Breaking change: Restarting functionality for now disabled.

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by ringholm** [comment]
I may suggest @bast or @bingao to review this work.

**Comment by bast** [comment]
Is it ready to go or are you planning more changes? (apart from our review)

**Review by bast — APPROVED** [review]
Thanks! If possible, I strongly suggest to not introduce out-commented code. In future it will not be clear why these are commented out. But for me this should not block the merge if there is nothing we can do about it due to time constraints.

**Comment by ringholm** [comment]
Sorry, I thought you reviewers would be the ones to put "ready to go" as your seal of approval. No, I didn't plan any more changes but skimming through the changes, I notice one or two missed cleanup opportunities (misleading comments). But it can be changed later in a general cleanup.

**Comment by ringholm** [comment]
Time constraints and time constraints, I mean if you as reviewers consider the restarting important enough then I guess some priorities can be changed, but then again we don't have formalized tests for the restarting and it may take longer to verify (and indeed be more difficult to verify fully, ref the discussions we have had before about this)

**Comment by bast** [comment]
I don't think restarting has to work. But I know that outcommented code is extremely problematic. For me there are two options:
- next to each outcommented portion we add a comment explaining why this is still there
- we remove the outcommented sections with a clear commit message and future generations can dig it out of the Git history books

**Comment by ringholm** [comment]
ok, I thought some more about this and I think that it would be a step forward if we merge this as it is now, and then I'll weave in some work to reinstate the restarting in a relatively decent shape and clean up some other smaller things before the release. We anyway planned to release the restarting functionality as an "at your own peril" thing with warnings, if i remember correctly, and considering the later move to python I just don't want to spend all my time in perfecting it.

**Comment by bast** [comment]
I agree with not perfecting this but please either annotate or remove outcommented code.

**Comment by bingao** [comment]
I agree with that we do not work any more on the restarting functionality for this release.

**Pull request merged**
