### PR TITLE
Remove legacy codes and change WEB file license

### PR DESCRIPTION
**Pull request by bingao**
To be done before release:

1. Look through RST files in the root directory and "doc" directory
2. Update "ChangeLog" if we still keep it
3. Update "openrsp.bib" if we still keep it
4. If time allowed, make the unit testing easier and optionally add more unit tests

### CODE REVIEW

**Review by bast — APPROVED** [review]
Thanks!

**Comment by bast** [comment]
I think the follow-up steps are better tracked as issues. Once I merge it this PR will be "closed".

**Comment by bingao** [comment]
OK. I agree and I will create an issue.

**Comment by bast** [comment]
And I recommend one issue per "issue". Then it's easier to solve them one by one.

**Pull request merged**
