### PR TITLE
Various residue fixes

### PR DESCRIPTION
**Pull request by ringholm**
## Description
* Changed rsp_tensor printing to detect "residue perturbations" and print their labels 'EX1' and 'EX2' instead of 'EL'. 'EX1' is used for perturbations involved in single residues and the "first residue" of a double residue. 'EX2' is used for the "second residue" of a double residue. However, double residues are not yet supported.
* Changed errors in adapter routines to quit program, not just print error message and move on
* Added stops for residue calculations that are unsupported, so program will stop in the following cases (non-residue calculations unaffected by this):
* More than one PROPERTY section
* More than one frequency configuration
* More than one excitation tuple
* Perturbation frequency sums (as opposed to frequencies of just one perturbation) intended to match the desired excitation energy
* Negative perturbation indices
* Double residues
* Updated test inside OpenRSP core routines to see if perturbation freqs. match the excitation energy: This test was not functioning as intended before. Also updated the detection threshold to 1e-6 (so this is the minimum precision w.r.t. which the intended "residue perturbation"'s frequency and the excited state energy difference w.r.t. the ground state must be)
* Removed some unused code to do with residues (I think it has had something to do with the incomplete(?) double residue functionality)

## Motivation and Context
This makes for safer running of the single residue functionality.

One thing I'm unsure of is whether to also restrict calculations where not all the (non-excitation) perturbations' frequencies are equal, i.e. we now allow both e.g.

lim (w_b -> w_N) <<A; B, C, D, ...>>_(w_c, w_d, ...)

where w_c, w_d etc. are all equal (which I think is "traditional" multiphoton absorption) and we also allow when they are not equal. Daniel (see https://gitlab.com/dalton/lsdalton/-/issues/40 ) has characterized the latter case as "not tested". So right now this latter case is still allowed but I don't know if it works and I don't know if I can test it. @bingao and @bast you are welcome to share your opinions on this and I also nominate you to review this entire PR. Maybe our "principle" of telling that it's "caveat emptor" for untested scenarios in the manual of LSDalton is sufficient diligence to allow this functionality to be accessed?

Another thing I've found is that I could only get results to match Dalton for HF calculations. Running with any XC functional seems to introduce errors (sometimes the answers are close, sometimes "weird but superficially plausible" elements are introduced, sometimes very strange elements are introduced. Some of this could be down to grid issues but I couldn't figure it out and I don't want to spend more time on this now.

## How Has This Been Tested?
I have tested all new error catches with LSDalton on my local laptop (there are also many newly written similar tests in the LSDalton OpenRSP wrapper and they should catch all these new restrictions before getting here. I wrote these additional restrictions in the (OpenRSP-side) adapter since they should also be restricted with other host programs). All LSDalton integration tests tagged 'openrsp' pass on my laptop. I have tested the single residue functionality and compared to Dalton for 2PA (first and 3rd excited state) and 3PA (first excited state). 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Contributor responsibilities
- [x] Every person who contributed to the contents of this pull request has read and understood and agree with the terms described in the contribution guidelines and documents concerning contribution and authorship topics linked to in the contribution guidelines, and the terms dictated by the license under which OpenRSP is released, and consent to the submission of their contributions to this pull request under these terms.
- [x] None of the submitted content in this pull request is licensed under terms which conflict with OpenRSP's license terms.
- [x] No person who is not currently an OpenRSP author has contributed to the content in this pull request, or someone in this category has contributed, and I have already or will immediately after submitting this pull request communicate their name(s) and contact information to the authors of OpenRSP.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by ringholm** [comment]
Once this is merged I can reference this on master in LSDalton and rm the WIP status from the analogous MR there.

**Review by bingao — APPROVED** [review]

**Comment by bingao** [comment]
Thank you @ringholm

**Comment by bingao** [comment]
Should we also delete the branch `residue_fixes`?

**Comment by bast** [comment]
Yes we should always delete source branches.

**Comment by bast** [comment]
(unless the source branch is master or a release branch)

**Comment by ringholm** [comment]
Thanks!

**Pull request merged**
