### PR TITLE
Website overhaul

### PR DESCRIPTION
**Pull request by ringholm**
Reorganization of website. Additionally collects changes made in former branches `website-overhaul-introduction` and `website-overhaul-howto`, and also contains various smaller changes to the text.

Now organized in "About the project" and "Accessing OpenRSP" sections. Further documentation can be added in appropriate places when ready.

This PR pertains to issue #42 but does not close it yet.

### CODE REVIEW

**Comment by ringholm** [comment]
I have a few suggestions for new issues about the website, but I will wait with posting them until this PR is merged since that would make the new version "official".

**Review by bingao — APPROVED** [review]

**Comment by ringholm** [comment]
Approved, so merging.

**Review by bast — APPROVED** [review]
Thank you! I am merging without looking through everything for two reasons:
- I am sure it's better than before.
- I will go through entire text anyway, easier for me to see the merged product rather than the diff.

**Comment by ringholm** [comment]
You beat me to it @bast :)

**Comment by bast** [comment]
https://thumbs.gfycat.com/MeagerCrazyGalapagossealion-size_restricted.gif

**Pull request merged**
