### PR TITLE
Remove myself from the list of OpenRSP authors (all occurrences in the repo)

### PR DESCRIPTION
**Pull request by ajthorva**
With this I cease to be an OpenRSP author and relinquish copyright to my
contributions to the project

### CODE REVIEW

**Comment by bast** [comment]
Hi Andreas, I will of course respect your wish but would like to understand why you prefer this and whether we can find a solution where you get the credit but perhaps don't have to be involved in decisions - if this is the motivation. Also feel free to reply via email.

**Comment by ajthorva** [comment]
I'm on the DOI for v1.0.0-alpha, which was desired, but don't want to be on future DOIs.

There are several reasons for this: 1) My current job is completely unrelated, and it's confusing that I (seemingly) still publish in chemistry; 2) Having a not too long author list may help attract new authors (higher impact/visibility per author); 3) I'm busy and see it as very unlikely that I will contribute significantly to future releases; 4) I don't think it's appropriate to participate in decisions without contributing to the execution of those decisions.

I'll remain a contributor, of course

**Review by bast — APPROVED** [review]

**Comment by bast** [comment]
The branch contains conflicts. I think Gao removed the tex files which you have modified.

**Comment by bast** [comment]
Thank you for the explanation!

**Comment by ringholm** [comment]
I am having some trouble merging this. I followed the command-line instructions above and when pushing I got

```
Writing objects: 100% (1/1), 246 bytes | 246.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/ajthorva/openrsp.git
 ! [remote rejected] master -> master (permission denied)
error: failed to push some refs to 'https://github.com/ajthorva/openrsp.git'
```

@bast Do you know what is going on here?

**Comment by robertodr** [comment]
It seems you're trying to push to Andreas' fork rather than this repo. What's your `origin`? That is, what does `git remote -v` show?

**Comment by ringholm** [comment]
Thanks @robertodr - indeed that was my mistake - I think I have handled everything here now.

**Pull request merged**
