### PR TITLE
One new author added for the release 1.0.0

### PR DESCRIPTION
**Pull request by bingao**

### CODE REVIEW

**Comment by bast** [comment]
I think the opinion of @foeroyingur and @simensr on this change is more important than my opinion.

**Comment by bingao** [comment]
OK, I remove the review requirement from you.

@KennethRuud and @foeroyingur could you please review this? @simensr is currently not in the group of OpenRSP.

**Comment by bingao** [comment]
Hei @bast 

If you think it is necessary to ask @simensr to review, please invite him to this group.

**Comment by bast** [comment]
No it is not necessary - everybody can comment here.

**Comment by foeroyingur** [comment]
I think I should not be added as author because I really haven't made any contribution.

**Comment by simensr** [comment]
I approve - thanks

**Comment by bast** [comment]
Good - Gao, can you please modify your commit accordingly? After that I will merge.

**Comment by bingao** [comment]
Hei Radovan,

I am sorry. But do you mean I need to make new commit and new pull request?

**Comment by bingao** [comment]
I do not know how to modify commit. Sorry.

**Comment by bast** [comment]
Now on phone. I will show you how within the next hour.

**Comment by ajthorva** [comment]
Edit the file, then commit it with `--amend`, then push the branch with `--force` (don't do this on master or other shared branches, though)

**Comment by bingao** [comment]
Thank you @ajthorva 

To @bast could you please confirm this pull request?

**Comment by bast** [comment]
The commit still contains two new authors. See the diff.

**Comment by bingao** [comment]
Sorry that I forgot to `git add` my changes. Now it should contain only one author.

**Comment by bast** [comment]
I am not a reviewer but I am merging using my superpowers.

**Comment by simensr** [comment]
Great - superpowers are good if they are not misused!!

Does this mean I can change the reference to OpenRSP in LSDalton, or is anything else missing?

**Comment by bast** [comment]
I think that's it - please update the reference on your side, please start the tests - if the tests are successful, then we can set the tag pointing to a2d6a7e5efb859943de7d7292b20ea2d39a837c9.

I will never misuse my permissions :-)

**Comment by simensr** [comment]
Ok, doing this now

**Pull request merged**
