### PR TITLE
Cleanup error printing; change print lvls for errors to two different kinds

### PR DESCRIPTION
**Pull request by ringholm**
## Description

Cleaned up some errors related to printing of output when OpenRSP encounters an error.

Introduced two print levels for errors: Sometimes we want to print several lines of information when an error is encountered. We don't want to exit until the last such line is printed. Now introduced two levels: One means "this line is about an error  - print it but do not quit". The other means "this line is about an error and is the last line to be printed about this error - print it and quit".

## Motivation and Context

Should be explained by above description.

## How Has This Been Tested?

Not tested yet - will look at results of LSDalton's OpenRSP tests to see if those tests pass. WIP status to be resolved once this is done (UPDATE: Now resolved and review can proceed). It's also possible to deliberately introduce errors and see if they result in the correct behavior. Can do this too but would not make a formal test for this now.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Status

- [ ]  Ready to go

### CODE REVIEW

**Comment by ringholm** [comment]
@bast Update: I induced an error that would trigger a several-line error print and it seems to have behaved correctly (printed all lines and quit after the last one). Without this induced error, all the OpenRSP tests pass for my local debug and release builds. Therefore WIP status can be removed and review can proceed.

**Comment by ringholm** [comment]
@bast Sorry for the back and forth - there will be a little more change before WIP is resolved.

**Comment by ringholm** [comment]
@bast We have now resolved the WIP and the review can proceed.

**Review by bast — APPROVED** [review]
Thanks! I assume the change is ready to be merged?

**Comment by ringholm** [comment]
Yes, if you are satisfied then it is ready to merge :)

**Pull request merged**
