### PR TITLE
Contribution guide and authorship process guide

### PR DESCRIPTION
**Pull request by ringholm**
## Description
I have written a draft for a contribution guide and a document describing the decision-making process we agreed on. This is not complete and I ask for comments or input.

## Motivation and Context
These will become the implemented guidelines that we discussed over the last year.

## Questions
@bast Is this an appropriate format for these two documents? I'm sure there are ways to improve this draft. @bingao in the AUTHOR_STATUS... file, would you please make some more "permanent" URLs for your documents as per @bast 's earlier comments about this and then update the links in this file?

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by bingao** [comment]
Hei @ringholm I will keep the links of these two documents for a while, so that there is no need to change them. Thank you for your nice work :-)

**Comment by bast** [comment]
I strongly recommend to change `master` in the links to a permalink which can be updated.

**Comment by bast** [comment]
As to the format this is a good starting point. Later we can move it to the documentation page if we see this as a better fit. But the `CONTRIBUTING.md` naming and placement is good.

**Comment by ringholm** [comment]
I am watching Radovan's "Research software hour" now and I now also recommend using a permalink :) I can probably take care of this myself.

**Comment by ringholm** [comment]
@bast I notice now that there is already a CONTRIBUTING.md in the .github/ folder. Is that the correct place for this kind of file? Should I move my new file into there and weave those two files together?

**Comment by ringholm** [comment]
I now merged the two CONTRIBUTING.md files into the file in the .github folder. I added permalinks for @bingao's documents. I updated the pull request template to contain boxes soliciting confirmation of author responsibilites.

As far as I'm concerned this PR is now ready for a "proper" review. I ask @bast or @bingao to take it from here.

**Comment by bast** [comment]
> @bast I notice now that there is already a CONTRIBUTING.md in the .github/ folder. Is that the correct place for this kind of file? Should I move my new file into there and weave those two files together?

Yes that's the right place. Sorry that I forgot we had that already.

**Review by bast — APPROVED** [review]

**Comment by bingao** [comment]
Hei @ringholm and @bast Thank you for taking care the link of authorship document :-)

**Pull request merged**
