### PR TITLE
Minor changes in README.rst; closes #3

### LINKED ISSUE #3: project website is openrsp.org
And not https://gitlab.com/openrsp.

### PR DESCRIPTION
**Pull request by bast**
Most importantly updated link to project website.

### CODE REVIEW

**Comment by ringholm** [comment]
Do you need to upgrade me from "Member" status to let me deal with this pull request?

**Review by ringholm — COMMENTED** [review]
Sure is some great work this here

**Review by ringholm — APPROVED** [review]
And I do most indubitably approve of this here fine craftsmanship

**Comment by bast** [comment]
I will check the team permissions - I might have missed something.

**Comment by ringholm** [comment]
Looks like you didn't need to upgrade me but I would appreciate being an owner :)

**Comment by bast** [comment]
OK good - glad it works since the goal was that members can merge. I will bump you to owner. This way you can add new people and I don't have to do it :-)

**Pull request merged**
